name: 'always-failed'
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/failed.yml
  workflow_dispatch:

jobs:
  failed:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
