name: 'always-success'
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/success.yml
  workflow_dispatch:

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
