name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
    paths:
      - "**.ts"
      - "**.json"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm install
      - run: npm run build
      # Currently we don't want to commit dist folder
      - uses: ./
        id: "check-success"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          currentRunId: ${{ github.run_id }}
          runnerLabel: "ubuntu-latest"
      - uses: ./
        id: "check-failed"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          currentRunId: 0  # we give an invalid run id which should result in an error
          runnerLabel: "ubuntu-latest"
      - name: Validate Result (If Statement)
        if: ${{ steps.check-success.outputs.foundRunningJob == true && steps.check-failed.outputs.foundRunningJob == false}}
        run: exit 0
      - name: Validate Result (Shell)
        run: |
          if [ '${{ steps.check-success.outputs.foundRunningJob }}' == true -a '${{ steps.check-failed.outputs.foundRunningJob }}' == false ]; then
            exit 0
          else
            exit 1
          fi

